### ISSUE TITLE
putBitmapOnDisk function, the process of java.lang.OutOfMemoryError is not.

### ISSUE THREAD

**Issue by erkasraim** [wuman/AndroidImageLoader#2]
Crash issue
putBitmapOnDisk function, the process of java.lang.OutOfMemoryError is not.

02-21 15:51:15.660: I/dalvikvm(13407): "LifoAsyncTask #3" prio=5 tid=17 RUNNABLE
02-21 15:51:15.660: I/dalvikvm(13407):   | group="main" sCount=0 dsCount=0 obj=0x436f5790 self=0x5e329dd0
02-21 15:51:15.660: I/dalvikvm(13407):   | sysTid=13660 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1580375192
02-21 15:51:15.660: I/dalvikvm(13407):   | schedstat=( 47014896620 14742726206 45724 ) utm=2156 stm=2545 core=2
02-21 15:51:15.660: I/dalvikvm(13407):   at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:~91)
02-21 15:51:15.660: I/dalvikvm(13407):   at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
02-21 15:51:15.660: I/dalvikvm(13407):   at android.graphics.Bitmap.nativeCompress(Native Method)
02-21 15:51:15.660: I/dalvikvm(13407):   at android.graphics.Bitmap.compress(Bitmap.java:772)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.ImageLoader$BitmapConverter.toStream(ImageLoader.java:942)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.ImageLoader.putBitmapOnDisk(ImageLoader.java:673)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.ImageLoader.access$1300(ImageLoader.java:61)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.ImageLoader$ImageRequest.writeBackResult(ImageLoader.java:873)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.ImageLoader$ImageTask.doInBackground(ImageLoader.java:887)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.ImageLoader$ImageTask.doInBackground(ImageLoader.java:879)
02-21 15:51:15.660: I/dalvikvm(13407):   at com.wuman.androidimageloader.util.LifoAsyncTask$2.call(LifoAsyncTask.java:126)
02-21 15:51:15.660: I/dalvikvm(13407):   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-21 15:51:15.660: I/dalvikvm(13407):   at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-21 15:51:15.660: I/dalvikvm(13407):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-21 15:51:15.660: I/dalvikvm(13407):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-21 15:51:15.660: I/dalvikvm(13407):   at java.lang.Thread.run(Thread.java:856)
02-21 15:51:15.660: W/System.err(13407): java.lang.OutOfMemoryError
02-21 15:51:15.660: W/System.err(13407):    at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
02-21 15:51:15.660: W/System.err(13407):    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
02-21 15:51:15.660: W/System.err(13407):    at android.graphics.Bitmap.nativeCompress(Native Method)
02-21 15:51:15.660: W/System.err(13407):    at android.graphics.Bitmap.compress(Bitmap.java:772)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.ImageLoader$BitmapConverter.toStream(ImageLoader.java:942)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.ImageLoader.putBitmapOnDisk(ImageLoader.java:673)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.ImageLoader.access$1300(ImageLoader.java:61)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.ImageLoader$ImageRequest.writeBackResult(ImageLoader.java:873)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.ImageLoader$ImageTask.doInBackground(ImageLoader.java:887)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.ImageLoader$ImageTask.doInBackground(ImageLoader.java:879)
02-21 15:51:15.660: W/System.err(13407):    at com.wuman.androidimageloader.util.LifoAsyncTask$2.call(LifoAsyncTask.java:126)
02-21 15:51:15.660: W/System.err(13407):    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
02-21 15:51:15.660: W/System.err(13407):    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
02-21 15:51:15.660: W/System.err(13407):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
02-21 15:51:15.660: W/System.err(13407):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
02-21 15:51:15.660: W/System.err(13407):    at java.lang.Thread.run(Thread.java:856)

**Comment by wuman** [comment]
Thanks for reporting this.  It is indeed an issue to be fixed.  I will work on a fix for this when I have time.  Otherwise feel free to send a pull request.
